# -*- coding: utf-8 -*-
"""Лаб2_КЛ_Безрукова .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQVFjbidnUsVkx5bQSVYc2nyyS365amk
"""

import nltk
from nltk import CFG
import IPython

!pip install svgling

import svgling

!pip install parse

import parse

from nltk.parse import RecursiveDescentParser

from nltk.parse import ShiftReduceParser

grammar = nltk.CFG.fromstring("""
  S -> NP VP 
  VP -> V PP | V NP | V NP PP | PV PP
  PV -> PA V
  VP -> AD
  PP -> P NP 
  V -> "шел" | "шла" | "упал" | "упала" | "побежала"
  NP ->  ADJ N | ADJ N PP | N PP | ADJ SUB | SUB
  SUB -> "Иван" | "Мария" | "Сергей"
  ADJ -> "Шустрая" | "своей" | "своему" | "большой" 
  N -> "подруге" | "кошке" | "дорогой" | "дому" | "дерева" | "собаке" | "Бегом"
  AD -> "бегом"
  P -> "в" | "с" | "к" | "вместе"
  PA -> "не"
  """)

parser = nltk.RecursiveDescentParser(grammar)
sent = 'Иван шел своей дорогой'.split() #разделяем строку на части
#trees=parser.parse(sent) #приводим к древовидному типу
for t in parser.parse(sent):
     print (t)

svgling.draw_tree(t)

parser = nltk.RecursiveDescentParser(grammar)
sent1 = 'Шустрая Мария не побежала к своей собаке'.split() #разделяем строку на части
#trees1=rd_parse.parse(sent1) #приводим к древовидному типу
for t1 in parser.parse(sent1):
     print (t1)

svgling.draw_tree(t1)